---
layout: post
title: "偏偏给我碰到Python C API的Bug?Py_Initialze()直接死循环"
categories:
- Python
tags:
- C++
- Python
status: publish
type: post
published: true
meta:
  ratings_users: '0'
  ratings_score: '0'
  ratings_average: '0'
  views: '15'
author:
  login: jtianling
  email: jtianling@gmail.com
  display_name: jtianling
  first_name: ''
  last_name: ''
---

<p><span style="font-size: small;">&nbsp;今天在一个程序中，在不同的两个函数，先用<span class="descname">Py_Initialize</span><big>(</big><big>)</big>初始化，然后用<span class="descname">Py_Finalize</span><big>(</big><big>)</big>结束，在本机都调试没有问题，然后将DLL发给同事后，老是在<span class="descname">Py_Initialize</span><big>(</big><big>)进入死循环，莫名其妙！怎么调试都没有用，奇怪了，然后将前一次的</big><span class="descname">Py_Finalize</span><big>(</big><big>)和</big><span class="descname">后一次Py_Initialize</span><big>(</big><big>)</big><big>的取消，也就是仅仅经过一次的</big><span class="descname">Py_Initialize</span><big>(</big><big>)，</big><span class="descname">Py_Finalize</span><big>(</big><big>)就完全没有问题。</big></span></p>
<p><span style="font-size: small;">这点也很奇怪，毕竟本机调试是没有任何问题的，在同事那里虽然换成了多线程环境，但是也没有道理总是必在<span class="descname">Py_Initialize</span><big>(</big><big>)死掉吧？看了Python的文档，才发现</big><span class="descname">Py_Finalize</span><big>(</big><big>)函数后有这么一段</big></span></p>
<p>&nbsp;</p>
<p><strong>Bugs and caveats:</strong> The destruction of modules and objects in<br />
modules is done in random order; this may cause destructors (<tt class="method">__del__()</tt> methods) to fail when they depend on other objects<br />
(even functions) or modules. Dynamically loaded extension modules loaded by<br />
Python are not unloaded. Small amounts of memory allocated by the Python<br />
interpreter may not be freed (if you find a leak, please report it). Memory tied<br />
up in circular references between objects is not freed. Some memory allocated by<br />
extension modules may not be freed. <span style="color: #ff0000;">Some extensions may not work properly if<br />
their initialization routine is called more than once;</span> <span style="color: #ff0000;">this can happen if an<br />
application calls <span class="cfunction">Py_Initialize()</span> and <span class="cfunction">Py_Finalize()</span> more than once. </span></p>
<p>&nbsp;</p>
<p><span style="color: #000000;">难道是这个问题？我这里也不是</span><span style="color: #000000;">extensions不工作的问题啊。。。。。。。或者还是多线程的问题？莫名奇妙啊。。。。。。</span></p>
<p>&nbsp;</p>
<p><span style="color: #000000;">这里顺便记个关于Python在对线程环境下工作的文章，明天去好好研究一下是什么问题。</span></p>
<h1>C++调用PythonAPI线程状态和全局解释器锁</h1>
<p><span style="color: #000000;">http://blog.csdn.net/marising/archive/2008/10/08/3032278.aspx</span></p>
<h1><cite class="fav_csdnstylebykimi"></cite></h1>
<p>&nbsp;</p>
<p><span style="color: #ff0000;"><br /></span></p>
